### ISSUE TITLE
Output Modified Character Spans

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#13]
### Description

- Provide an output about the spans of text that were modified.

### Tasks

- [x] Replace Dicts structure in pipeline by actual structure.
- [x] Add metadata field to output for each sentence.
- [x] Masking output with masked spans.
- [x] Add modified spans for `transf-swp-ne`, `transf-swp-num` and `transf-ins-text` (from `MaskAndFill` transform).
- [x] Remove modified spans on validation steps when removing perturbation.
- [ ] ~Better format json outputs to not break small lists.~ (Reason: python json module not that customisable.)
