### ISSUE TITLE
Data structure for data transfer

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#18]
### Description

* Generic structure to transfer data.
* This structure should support promotion and broadcasting for chaining of operations.

### Tasks

- [x] Data structure to transfer data.
- [x] Promotion rules to create Data objects.
- [x] Move available operations to use Data structure.
