### ISSUE TITLE
Random Generators as mandatory parameters

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#22]
### Description

Random generators are currently inserted inside the functions with a global function setting seeds.
Number generators should be received as non optional parameters to force reproducibility.

### Tasks

- [ ] Add `rng` argument to functions that require random generators.
- [ ] Remove `random.numpy_seeded_rng()` from these functions.
- [ ] `random` should be a `random.py` file and not a module.
