### ISSUE TITLE
Avoid model auto caching

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#23]
### Description

Current ops that require modules have a load function that cache the models, which can lead to higher memory consumption when the model is not longer required.

### Tasks

- [x] Remove caching from model loading.
- [x] Functions should receive models as arguments.
- [x] Model loading should be separated from operations.
