### ISSUE TITLE
Immutable Sentence that stores modifications.

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#34]
### Description

The sentence object should be similar to str, being immutable as well.
Furthermore, it should provide a way to trace modifications (as well as modified spans).

### Tasks

- [x] Create sentence object with `insert`, `delete` and `replace` operations.
- [x] Create trace modifications method to gather all modifications applied to a given sentence.
- [x] Update ops to use sentence objects.
- [x] Update validations to use sentence objects.
- [x] Update transforms to use sentence objects.
- [x] Update cli ops to use sentence objects.
