### ISSUE TITLE
Create perturbations API

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#48]
### Description

The perturbations (transforms with default validations) are only available as CLI commands.
They should be a separate module that is part of the `smaug` API.
The cli should then call this module.

### Tasks

- [x] Create API using the pipeline struct.
- [x] Move API to sentences.
- [x] Create package with entire API.
- [x] Move pipeline to cli.
- [x] Document API.
